# Generated by Django 5.0.7 on 2025-11-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de pedido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuestos')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pagado_en', models.DateTimeField(blank=True, null=True, verbose_name='Pagado el')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('entregado_en', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('variante_info', models.JSONField(blank=True, null=True, verbose_name='Información de variante')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='Referencia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direccion_envio', to='ventas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Dirección de Envío',
                'verbose_name_plural': 'Direcciones de Envío',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='ventas_pedi_numero__de1308_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-creado'], name='ventas_pedi_usuario_718a07_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='ventas_pedi_estado_f9d43e_idx'),
        ),
    ]
