# Generated by Django 5.0.7 on 2025-11-11 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token FCM')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20, verbose_name='Tipo de dispositivo')),
                ('device_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del dispositivo')),
                ('is_active', models.BooleanField(default=True, help_text='Desactivar si el token ya no es válido', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'db_table': 'device_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx'), models.Index(fields=['token'], name='device_toke_token_e218ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, help_text='Topic de Firebase para notificaciones masivas', max_length=100, null=True, verbose_name='Topic')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('promo', 'Promoción'), ('pedido', 'Pedido'), ('mensaje', 'Mensaje'), ('alerta', 'Alerta'), ('sistema', 'Sistema')], default='info', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('data', models.JSONField(blank=True, help_text='Datos personalizados en formato JSON', null=True, verbose_name='Datos adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('leida', 'Leída')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('message_id', models.CharField(blank=True, help_text='ID retornado por Firebase al enviar', max_length=255, null=True, verbose_name='ID de mensaje FCM')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(blank=True, help_text='Dejar en blanco para notificaciones a topics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'estado'], name='notificatio_user_id_1e6768_idx'), models.Index(fields=['tipo', 'estado'], name='notificatio_tipo_563d7d_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
