# Generated by Django 5.0.7 on 2025-11-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Para usuarios anónimos', max_length=255, null=True, verbose_name='ID de Sesión')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de agregar al carrito', max_digits=10, verbose_name='Precio unitario')),
                ('agregado', models.DateTimeField(auto_now_add=True, verbose_name='Agregado el')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito', verbose_name='Carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='productos.producto', verbose_name='Producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='productos.productovariante', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'ordering': ['agregado'],
            },
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario'], name='carrito_car_usuario_d0e2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['session_key'], name='carrito_car_session_4b2343_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'variante')},
        ),
    ]
