# Generated by Django 5.0.7 on 2025-11-12 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_original', models.TextField(help_text='Comando de voz o texto ingresado por el usuario', verbose_name='Prompt Original')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('productos', 'Productos'), ('clientes', 'Clientes'), ('ingresos', 'Ingresos')], max_length=20, verbose_name='Tipo de Reporte')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('agrupacion', models.CharField(choices=[('producto', 'Por Producto'), ('cliente', 'Por Cliente'), ('categoria', 'Por Categoría'), ('fecha', 'Por Fecha'), ('ninguno', 'Sin Agrupación')], default='ninguno', max_length=20, verbose_name='Agrupación')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON')], max_length=10, verbose_name='Formato')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/', verbose_name='Archivo Generado')),
                ('datos_json', models.JSONField(blank=True, help_text='Datos en formato JSON para reutilización', null=True, verbose_name='Datos del Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='reportes_re_created_b3de31_idx'), models.Index(fields=['usuario', '-created_at'], name='reportes_re_usuario_bf2175_idx'), models.Index(fields=['tipo', '-created_at'], name='reportes_re_tipo_ad2023_idx')],
            },
        ),
    ]
