# Generated by Django 5.0.7 on 2025-11-26 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del indicador')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('umbral_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral Mínimo')),
                ('umbral_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Umbral Máximo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Alerta',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('MES', 'Mes'), ('TRIMESTRE', 'Trimestre'), ('AÑO', 'Año')], max_length=20, verbose_name='Tipo de periodo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='Mes (1-12)')),
                ('trimestre', models.IntegerField(blank=True, null=True, verbose_name='Trimestre (1-4)')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de cierre')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='afp.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Periodo Financiero',
                'verbose_name_plural': 'Periodos Financieros',
                'ordering': ['-año', '-mes', '-trimestre', '-version'],
                'unique_together': {('empresa', 'tipo_periodo', 'año', 'mes', 'trimestre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FlujoEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Utilidad Neta')),
                ('ajustes_depreciacion', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Depreciación y Amortización')),
                ('cambios_capital_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cambios en Capital de Trabajo')),
                ('flujo_operativo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Flujo de Efectivo Operativo')),
                ('compras_activos_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Compras de Activos Fijos')),
                ('ventas_activos_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ventas de Activos Fijos')),
                ('flujo_inversion', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Flujo de Efectivo de Inversión')),
                ('prestamos_recibidos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Préstamos Recibidos')),
                ('pago_prestamos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pago de Préstamos')),
                ('flujo_financiamiento', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Flujo de Efectivo de Financiamiento')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flujo_efectivo', to='afp.periodofinanciero', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Flujo de Efectivo',
                'verbose_name_plural': 'Flujos de Efectivo',
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas_netas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ventas Netas')),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Ingresos')),
                ('costo_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Costo de Ventas (COGS)')),
                ('gastos_operativos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gastos Operativos')),
                ('gastos_financieros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gastos Financieros')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impuestos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_resultados', to='afp.periodofinanciero', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Estado de Resultados',
                'verbose_name_plural': 'Estados de Resultados',
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja_bancos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Caja y Bancos')),
                ('cuentas_por_cobrar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cuentas por Cobrar')),
                ('inventarios', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Inventarios')),
                ('otros_activos_corrientes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Activos Corrientes')),
                ('propiedades_planta_equipo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Propiedades, Planta y Equipo')),
                ('inversiones_largo_plazo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Inversiones a Largo Plazo')),
                ('intangibles', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Activos Intangibles')),
                ('otros_activos_no_corrientes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Activos No Corrientes')),
                ('cuentas_por_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cuentas por Pagar')),
                ('prestamos_corto_plazo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Préstamos a Corto Plazo')),
                ('pasivos_acreedores', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pasivos con Acreedores')),
                ('otros_pasivos_corrientes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Pasivos Corrientes')),
                ('prestamos_largo_plazo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Préstamos a Largo Plazo')),
                ('otros_pasivos_no_corrientes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Pasivos No Corrientes')),
                ('capital_social', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Capital Social')),
                ('reservas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Reservas')),
                ('utilidades_acumuladas', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Utilidades Acumuladas')),
                ('otros_patrimonios', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Otros Patrimonios')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_general', to='afp.periodofinanciero', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Balance General',
                'verbose_name_plural': 'Balances Generales',
            },
        ),
    ]
