# Generated by Django 5.0.7 on 2025-11-11 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del método')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'Código QR'), ('efectivo', 'Efectivo'), ('wallet', 'Billetera Digital')], max_length=20)),
                ('proveedor', models.CharField(choices=[('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('paypal', 'PayPal'), ('manual', 'Manual')], max_length=20)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Comisión del proveedor en porcentaje', max_digits=5, verbose_name='Comisión (%)')),
                ('comision_fija', models.DecimalField(decimal_places=2, default=0, help_text='Comisión fija por transacción', max_digits=10, verbose_name='Comisión fija')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica del proveedor', verbose_name='Configuración adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(editable=False, help_text='Número único de orden generado automáticamente', max_length=50, unique=True, verbose_name='Número de orden')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='BOB', max_length=3, verbose_name='Moneda')),
                ('comision', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Comisión')),
                ('monto_neto', models.DecimalField(decimal_places=2, help_text='Monto - comisión', max_digits=12, verbose_name='Monto neto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('reembolso_parcial', 'Reembolso Parcial')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(verbose_name='Descripción del pago')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='MercadoPago Payment ID')),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia externa')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadata')),
                ('cliente_nombre', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('cliente_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_facturacion', models.JSONField(blank=True, default=dict, verbose_name='Dirección de facturación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pagado_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.metodopago', verbose_name='Método de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto a reembolsar')),
                ('motivo', models.CharField(choices=[('solicitud_cliente', 'Solicitud del Cliente'), ('producto_defectuoso', 'Producto Defectuoso'), ('error_sistema', 'Error del Sistema'), ('duplicado', 'Pago Duplicado'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField(verbose_name='Descripción del motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercadopago_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='payments.pago', verbose_name='Pago')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reembolsos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Reembolso',
                'verbose_name_plural': 'Reembolsos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('reembolso', 'Reembolso'), ('cargo', 'Cargo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='ID externo')),
                ('descripcion', models.TextField(blank=True)),
                ('exitosa', models.BooleanField(default=True)),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='payments.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=50, verbose_name='Proveedor')),
                ('evento_tipo', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(verbose_name='Payload completo')),
                ('headers', models.JSONField(default=dict, verbose_name='Headers HTTP')),
                ('procesado', models.BooleanField(default=False)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, verbose_name='Error al procesar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.pago')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['-created_at'], name='payments_pa_created_d5e6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado'], name='payments_pa_estado_ff77c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['usuario', '-created_at'], name='payments_pa_usuario_dff85d_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['numero_orden'], name='payments_pa_numero__69a2b3_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['proveedor', '-created_at'], name='payments_we_proveed_2442a2_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['procesado'], name='payments_we_procesa_df4dd5_idx'),
        ),
    ]
