# Generated by Django 5.0.7 on 2025-11-11 20:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve para las tarjetas de producto', max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descuento_porcentaje', models.IntegerField(default=0, help_text='Porcentaje de descuento (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio_oferta', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_oferta', models.DateTimeField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta cuando el stock sea menor o igual a este valor')),
                ('meses_garantia', models.IntegerField(default=12, help_text='Meses de garantía del producto', validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion_garantia', models.TextField(default='Garantía del fabricante', help_text='Descripción detallada de la garantía')),
                ('sku', models.CharField(blank=True, help_text='Código único del producto (Stock Keeping Unit)', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=8, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Producto visible en la tienda')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en sección destacados')),
                ('vistas', models.IntegerField(default=0, help_text='Número de visitas al producto')),
                ('ventas', models.IntegerField(default=0, help_text='Cantidad de unidades vendidas')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('es_principal', models.BooleanField(default=False, help_text='Imagen principal del producto')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('alt_text', models.CharField(blank=True, help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen del Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['orden', '-es_principal'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Rojo - M', 'Azul - L', '128GB'", max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio adicional sobre el precio base', max_digits=10)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Variante del Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_p_categor_5dba6d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='productos_p_slug_5e4b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['sku'], name='productos_p_sku_610a4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'nombre')},
        ),
    ]
