# Generated by Django 5.0.7 on 2025-11-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/'),
        ),
    ]
