# Generated by Django 5.0.7 on 2025-11-12 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del método')),
                ('tipo', models.CharField(choices=[('STRIPE', 'Tarjeta de Crédito/Débito (Stripe)'), ('PAYPAL', 'PayPal'), ('QR', 'QR Bolivia'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria')], max_length=20, verbose_name='Tipo de pago')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración específica del método de pago')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(default='BOB', max_length=3, verbose_name='Moneda')),
                ('id_externo', models.CharField(blank=True, help_text='Payment Intent ID, Transaction ID, etc.', max_length=255, null=True, verbose_name='ID de transacción externa')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional de la transacción (respuesta del gateway, etc.)')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de error')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='pagos.metodopago', verbose_name='Método de pago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='ventas.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['pedido', '-creado'], name='pagos_trans_pedido__cc93f2_idx'), models.Index(fields=['estado'], name='pagos_trans_estado_ee196a_idx'), models.Index(fields=['id_externo'], name='pagos_trans_id_exte_d9ea43_idx')],
            },
        ),
    ]
